### ISSUE TITLE
Doesn't connect with proxy

### ISSUE THREAD

**Issue by malygin-g** [noobot/SlackConnector#73]
Hi, I can't connect with proxy:
p.s. The error seems to be with the nuget library is WebsocketClientLite.PCL
System.InvalidOperationException
HResult=0x80131509
Message=The operation is not allowed on non-connected sockets.
Source=System
StackTrace:
at System.Net.Sockets.TcpClient.GetStream()
at SocketLite.Services.TcpSocketClient.<ConnectAsync>d__19.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at WebsocketClientLite.PCL.MessageWebSocketRx.<CreateObservableMessageReceiver>d__15.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SlackConnector.Connections.Sockets.WebSocketClientLite.<Connect>d__7.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SlackConnector.Connections.ConnectionFactory.<CreateWebSocketClient>d__0.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SlackConnector.SlackConnector.<Connect>d__5.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at TopShelf2.SlackConnect.<Connect>d__4.MoveNext() in C:\mygit\TopShelf2\TopShelf2\Program.cs:line 40

**Comment by Workshop2** [comment]
@malygin-g can you post this on that nuget library issues? https://github.com/1iveowl/WebsocketClientLite.PCL/issues
